name: ntplacesbot

on:
  #schedule:
   # - cron: '14 9/8 * * *'
   push:
    branches:
      - main

jobs:
  ntplacesbot-post:
    runs-on macOS-latest
    env:
      TWITTER_CONSUMER_API_KEY: ${{ secrets.BOT_TwitterAPIkey }}
      TWITTER_CONSUMER_API_SECRET: ${{ secrets.BOT_TwitterAPIsecretkey }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.BOT_TwitterAccessTokenSecret }}
      MAPBOX_PUBLIC_ACCESS_TOKEN: ${{ secrets.BOT_TwitterAccessToken }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - name: Install rtweet package
        run: Rscript -e 'install.packages("rtweet", dependencies = TRUE)'
      - name: Create and post tweet
        run: Rscript twitter-bot.r