name: ntplacesbot
on:
  #schedule:
   # - cron: '14 9/8 * * *'
   push:
    branches:
      - main
jobs:
  ntplacesbot-post:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
        with: 
          use-public-rspm: true
      - name: Install cURL Headers
        run: |
          sudo apt-get update
          sudo apt-get install libcurl4-openssl-dev
      - name: Install packages
        run: Rscript -e 'source("R/pkg_install.R")' -e 'install_packages()'
      - name: Post the Tweet
        run: Rscript twitter-bot.r
    env:
      TWITTER_CONSUMER_API_KEY: ${{ secrets.BOT_TWITTERAPIKEY }}
      TWITTER_CONSUMER_API_SECRET: ${{ secrets.BOT_TWITTERAPISECRETKEY }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.BOT_TWITTERACCESSTOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.BOT_TWITTERACCESSTOKENSECRET }}
