name: ntplacesbot
on:
  #schedule:
   # - cron: '30 9,15,20 * * *'  # trigger at 09:30, 15:30, 20:30 every day
    push:
     branches:
       - main
jobs:
  ntplacesbot-post:
    runs-on: macOS-latest
    
    steps:
      - uses: actions/checkout@main
      - uses: r-lib/actions/setup-r@v2
      - name: Install googlesheets4 package
        run: Rscript -e 'install.packages("googlesheets4", dependencies = TRUE)'
      - name: Install rtweet package
        run: Rscript -e 'install.packages("rtweet", dependencies = TRUE)'
      - name: Install dplyr package
        run: Rscript -e 'install.packages("dplyr", dependencies = TRUE)'
      - name: Post the Tweet
        run: Rscript twitter-bot.r
    env:
      TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
      TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
