name: ntplacesbot
on:
  #schedule:
   # - cron: '14 9/8 * * *'
   push:
    branches:
      - main
jobs:
  ntplacesbot-post:
    runs-on: macOS-latest
    
    steps:
      - uses: actions/checkout@main
      - uses: r-lib/actions/setup-r@v2
      - name: Install googlesheets4 package
        run: Rscript -e 'install.packages("googlesheets4", dependencies = TRUE)'
      - name: Install rtweet package
        run: Rscript -e 'install.packages("rtweet", dependencies = TRUE)'
      - name: Install dplyr package
        run: Rscript -e 'install.packages("dplyr", dependencies = TRUE)'
      - name: Install tidyr package
        run: Rscript -e 'install.packages("tidyr", dependencies = TRUE)'
      - name: Install stringr package
        run: Rscript -e 'install.packages("stringr", dependencies = TRUE)'  
      - name: Create and post tweet
        run: Rscript twitter-bot.r
    env:
      TWITTER_CONSUMER_API_KEY: ${{ secrets.BOT_TWITTERAPIKEY }}
      TWITTER_CONSUMER_API_SECRET: ${{ secrets.BOT_TWITTERAPISECRETKEY }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.BOT_TWITTERACCESSTOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.BOT_TWITTERACCESSTOKENSECRET }}
